import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {importProducts,setQuantity,placeOrder,updateOrder,bookVisit,slotsFor,validateHours,validateProduct,safeImage,escapeHTML} from '../public/domain.js';
const customer={name:'Demo Visitor',phone:'01700000000',address:'Demo address, Chattogram'};
function state(){return {products:[{id:'p1',name:'Demo cleanser',price:100,stock:3,active:true,category:'Skin care'}],cart:[],orders:[],bookings:[],settings:{shipping:20,hours:['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(day=>({day,open:'09:00',close:'17:00',closed:false}))},services:[{id:'s1',name:'Consultation',active:true}],experts:[{id:'e1',name:'Demo Expert',active:true}]}}
test('imports all 72 supplied products and preserves missing prices',async()=>{const p=importProducts(await readFile(new URL('../public/products.csv',import.meta.url),'utf8'));assert.equal(p.length,72);assert.equal(p.filter(x=>x.price===null).length,5);assert.ok(p.every(x=>Number.isInteger(x.stock)&&x.stock>=0))});
test('cart persists quantities, rejects overstock, and removes hidden products',()=>{const s=state();setQuantity(s,'p1',2);assert.deepEqual(s.cart,[{id:'p1',qty:2}]);assert.throws(()=>setQuantity(s,'p1',4),/stock/);s.products[0].active=false;setQuantity(s,'p1',0);assert.equal(s.cart.length,0);assert.throws(()=>setQuantity(s,'p1',1),/unavailable/)});
test('checkout snapshots prices and reserves inventory; cancellation restores exactly once',()=>{const s=state();setQuantity(s,'p1',2);const o=placeOrder(s,customer);assert.equal(o.total,220);assert.equal(s.products[0].stock,1);assert.equal(s.cart.length,0);s.products[0].price=900;assert.equal(o.lines[0].price,100);updateOrder(s,o.id,'Cancelled');updateOrder(s,o.id,'Cancelled');assert.equal(s.products[0].stock,3);assert.throws(()=>updateOrder(s,o.id,'Confirmed'),/cannot be reopened/)});
test('failed checkout does not change inventory or orders',()=>{const s=state();setQuantity(s,'p1',2);assert.throws(()=>placeOrder(s,{...customer,phone:'123'}),/mobile/);s.products[0].stock=1;assert.throws(()=>placeOrder(s,customer),/quantity/);assert.equal(s.orders.length,0);assert.equal(s.cart.length,1);assert.equal(s.products[0].stock,1)});
test('missing prices cannot be ordered and invalid stock is rejected',()=>{const s=state();s.products[0].price=null;assert.throws(()=>setQuantity(s,'p1',1),/price/);assert.throws(()=>validateProduct({...s.products[0],stock:1.5}),/whole number/)});
test('booking respects hours and prevents double booking for the same expert',()=>{const s=state();const date='2099-09-10';assert.equal(slotsFor(s,date).length,16);const input={...customer,serviceId:'s1',expertId:'e1',date,time:'09:00'};bookVisit(s,input);assert.equal(s.bookings.length,1);assert.throws(()=>bookVisit(s,input),/already/);s.bookings[0].status='Cancelled';bookVisit(s,input);assert.equal(s.bookings.length,2);assert.throws(()=>bookVisit(s,{...input,time:'17:00'}),/future appointment/)});
test('closed days, invalid dates, and malformed hours have no bookable flow',()=>{const s=state();s.settings.hours.forEach(h=>h.closed=true);assert.deepEqual(slotsFor(s,'2099-09-10'),[]);assert.deepEqual(slotsFor(s,'2099-02-31'),[]);assert.deepEqual(slotsFor(s,'2000-01-01'),[]);const h=state().settings.hours;h[0].open='09:99';assert.throws(()=>validateHours(h),/valid opening/);h[0].closed=true;h[1].day='Sunday';assert.throws(()=>validateHours(h),/seven days/)});
test('editable HTML and unsafe image schemes cannot become script',()=>{assert.equal(safeImage('javascript:alert(1)'),'');assert.equal(safeImage('data:image/svg+xml,<svg onload=alert(1)>'),'');assert.equal(escapeHTML('<img src=x onerror="x">'),'&lt;img src=x onerror=&quot;x&quot;&gt;')});
