import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=join(dirname(fileURLToPath(import.meta.url)),'..');
const csv=await readFile(join(root,'public','products.csv'),'utf8');
const originalFetch=globalThis.fetch;
globalThis.fetch=async input=>String(input)==='/products.csv'?{ok:true,text:async()=>csv}:originalFetch(input);
const {seedState}=await import('../public/data.js');
const seed=await seedState();
const output=join(root,'api','_lib','seed.js');
await mkdir(dirname(output),{recursive:true});
await writeFile(output,`// Generated by scripts/write-seed.mjs.\nexport default ${JSON.stringify(seed)};\n`,'utf8');
